server:
  port: 9002
spring:
  application:
    name: eureka-client
    # 用於鏈路跟蹤，需要下載zipkin-server，9411是其端口
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 0.1 # 抽樣概率
eureka:
#  instance:
#    instanceId: ${spring.application.name}
#    instance-id: ${spring.cloud.client.ip-address}:${server.port}
#    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
#      defaultZone: http://eureka01:8220/eureka/,http://eureka02:8221/eureka/,http://eureka03:8222/eureka/
      # 單個
      defaultZone: http://localhost:8220/eureka/
