server:
  port: 9002
spring:
  application:
    name: eureka-client
eureka:
#  instance:
#    instanceId: ${spring.application.name}
#    instance-id: ${spring.cloud.client.ip-address}:${server.port}
#    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
#      defaultZone: http://eureka01:8220/eureka/,http://eureka02:8221/eureka/,http://eureka03:8222/eureka/
      # 單個
      defaultZone: http://localhost:8220/eureka/
